<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUc5mk84\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUc5mk84/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUc5mk84.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUc5mk84\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUc5mk84\appProdProjectContainer([
    'container.build_hash' => 'Uc5mk84',
    'container.build_id' => 'd287df0f',
    'container.build_time' => 1641497509,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUc5mk84');
