<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2nq0q9c\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2nq0q9c/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2nq0q9c.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2nq0q9c\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2nq0q9c\appProdProjectContainer([
    'container.build_hash' => '2nq0q9c',
    'container.build_id' => '77462c52',
    'container.build_time' => 1636937996,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2nq0q9c');
